# 2026 год, Go 1.26
FROM golang:1.26-bookworm AS base

RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config build-essential wget tar git mingw-w64 autoconf automake libtool \
    libx11-dev libxcb1-dev libxau-dev libxdmcp-dev libasound2-dev libpulse-dev \
    bash coreutils cmake unzip python3 libwebp-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

ARG VERSION=1.0.0
ARG APP_ENV=prod
ARG OPENCV_VERSION=4.10.0

# --- СБОРКА LINUX (Динамическая) ---
FROM base AS build-linux
ENV GOOS=linux
ENV GOARCH=amd64
ENV CGO_ENABLED=1
ENV PREFIX=/usr/local

WORKDIR /tmp/build
# 1. OpenCV (Minimal)
RUN wget -O opencv.zip https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.zip && \
    unzip opencv.zip && mkdir -p opencv-build && cd opencv-build && \
    cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=${PREFIX} \
          -D BUILD_LIST=core,videoio,imgproc,imgcodecs -D WITH_V4L=ON -D WITH_WEBP=ON \
          -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_DOCS=OFF \
          ../opencv-${OPENCV_VERSION} && make -j$(nproc) && make install

# 2. Звуковые либы (OGG, Opus, Speex, RNNoise)
RUN wget https://downloads.xiph.org/releases/ogg/libogg-1.3.5.tar.gz && tar -xzf libogg-1.3.5.tar.gz && cd libogg-1.3.5 && ./configure --prefix=${PREFIX} --enable-shared --disable-static && make -j$(nproc) && make install
RUN wget https://downloads.xiph.org/releases/opus/opus-1.4.tar.gz && tar -xzf opus-1.4.tar.gz && cd opus-1.4 && ./configure --prefix=${PREFIX} --enable-shared --disable-static --disable-extra-programs && make -j$(nproc) && make install
RUN wget https://downloads.xiph.org/releases/opus/opusfile-0.12.tar.gz && tar -xzf opusfile-0.12.tar.gz && cd opusfile-0.12 && CFLAGS="-I${PREFIX}/include" LDFLAGS="-L${PREFIX}/lib" ./configure --prefix=${PREFIX} --enable-shared --disable-static --disable-http && make -j$(nproc) && make install
RUN wget https://downloads.xiph.org/releases/speex/speexdsp-1.2.1.tar.gz && tar -xzf speexdsp-1.2.1.tar.gz && cd speexdsp-1.2.1 && ./configure --prefix=${PREFIX} --enable-shared --disable-static && make -j$(nproc) && make install
RUN git clone https://github.com/xiph/rnnoise.git && cd rnnoise && ./autogen.sh && ./configure --prefix=${PREFIX} --enable-shared --disable-static && make -j$(nproc) && make install

WORKDIR /app
ENV CGO_CFLAGS="-I${PREFIX}/include/opencv4 -I${PREFIX}/include"
ENV CGO_LDFLAGS="-L${PREFIX}/lib -lopencv_core -lopencv_videoio -lopencv_imgproc -lopencv_imgcodecs -lopusfile -lopus -logg -lspeexdsp -lrnnoise -lX11 -lm"

RUN mkdir -p /out/libs && \
    go build -tags netgo,osusergo -ldflags="-s -w -X 'main.version=${VERSION}' -X 'main.env=${APP_ENV}'" -o /out/aloh ./cmd/app && \
    cp -P ${PREFIX}/lib/*.so* /out/libs/ 2>/dev/null || true && \
    tar cfvz /out/aloh.zip -C /out aloh libs/

# --- СБОРКА WINDOWS (Статическая) ---
FROM base AS build-windows
ENV GOOS=windows
ENV GOARCH=amd64
ENV CGO_ENABLED=1
ENV HOST=x86_64-w64-mingw32
ENV CC=x86_64-w64-mingw32-gcc
ENV CXX=x86_64-w64-mingw32-g++
ENV PREFIX=/usr/x86_64-w64-mingw32

# ПЕРЕКЛЮЧЕНИЕ MinGW на POSIX Threads (Критично для std::mutex в OpenCV)
RUN update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix && \
    update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix

WORKDIR /tmp/build

# 1. OpenCV (Static для MinGW)
RUN wget -O opencv.zip https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.zip && \
    unzip opencv.zip && mkdir -p opencv-win-build && cd opencv-win-build && \
    cmake -D CMAKE_SYSTEM_NAME=Windows -D CMAKE_C_COMPILER=${CC} -D CMAKE_CXX_COMPILER=${CXX} \
          -D CMAKE_RC_COMPILER=x86_64-w64-mingw32-windres -D CMAKE_INSTALL_PREFIX=${PREFIX} \
          -D BUILD_SHARED_LIBS=OFF -D BUILD_LIST=core,videoio,imgproc,imgcodecs \
          -D WITH_MSMF=ON -D WITH_DSHOW=ON -D WITH_WEBP=ON -D BUILD_WEBP=ON \
          -D WITH_OPENEXR=OFF -D WITH_TIFF=OFF -D BUILD_JPEG=ON -D BUILD_ZLIB=ON \
          -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF \
          ../opencv-${OPENCV_VERSION} && make -j$(nproc) && make install

# 2. Звуковые либы (Static)
RUN wget https://downloads.xiph.org/releases/ogg/libogg-1.3.5.tar.gz && tar -xzf libogg-1.3.5.tar.gz && cd libogg-1.3.5 && ./configure --host=${HOST} --prefix=${PREFIX} --disable-shared --enable-static && make -j$(nproc) && make install
RUN wget https://downloads.xiph.org/releases/opus/opus-1.4.tar.gz && tar -xzf opus-1.4.tar.gz && cd opus-1.4 && ./configure --host=${HOST} --prefix=${PREFIX} --disable-shared --enable-static --disable-extra-programs && make -j$(nproc) && make install
RUN wget https://downloads.xiph.org/releases/opus/opusfile-0.12.tar.gz && tar -xzf opusfile-0.12.tar.gz && cd opusfile-0.12 && CFLAGS="-I${PREFIX}/include" LDFLAGS="-L${PREFIX}/lib" ./configure --host=${HOST} --prefix=${PREFIX} --disable-shared --enable-static --disable-http && make -j$(nproc) && make install
RUN git clone https://github.com/xiph/rnnoise.git && cd rnnoise && ./autogen.sh && ./configure --host=${HOST} --prefix=${PREFIX} --disable-shared --enable-static && make -j$(nproc) && make install
RUN wget https://downloads.xiph.org/releases/speex/speexdsp-1.2.1.tar.gz && tar -xzf speexdsp-1.2.1.tar.gz && cd speexdsp-1.2.1 && ./configure --host=${HOST} --prefix=${PREFIX} --disable-shared --enable-static && make -j$(nproc) && make install

WORKDIR /app
# Важно: для OpenCV 4.10 либы называются opencv_core4100
ENV CGO_CFLAGS="-I${PREFIX}/include/opencv4 -I${PREFIX}/include -Wno-stringop-overflow"
ENV CGO_LDFLAGS="-L${PREFIX}/lib -Wl,--start-group -lopencv_core4100 -lopencv_videoio4100 -lopencv_imgproc4100 -lopencv_imgcodecs4100 -lzlib -llibwebp -lopusfile -lopus -logg -lspeexdsp -lrnnoise -Wl,--end-group -lm -lpthread -lws2_32 -lole32 -lgdi32 -lcomdlg32 -lavifil32 -lmsvfw32 -loleaut32 -luuid"

RUN mkdir -p /out && \
    go build -tags netgo,osusergo -ldflags="-s -w -extldflags '-static' -X 'main.version=${VERSION}' -X 'main.env=${APP_ENV}'" -o /out/aloh.exe ./cmd/app && \
    tar cfvz /out/aloh.zip -C /out aloh.exe

# --- ЭКСПОРТ ---
FROM scratch AS export
COPY --from=build-linux /out/aloh.zip /linux/
COPY --from=build-windows /out/aloh.zip /windows/