app:
  name: "aloh-networking"
  version: "1.0.0"
  env: "local"
  receiveSDPSize: 100
  sendSDPSize: 100
  logPath: ""

signaling:
  address: "164.90.163.153"
  port: "1234"
  handshakeTimeout: 10s
  maxIdleTimeout: 60s
  keepAlivePeriodTimeout: 10s
  closeTimeout: 10s
  startTimeout: 10s
  nextProtos: ["aloh-proto"]
  maxIncomingStreams: 100
  regTimeout: 10s

networking:
  handshakeTimeout: 10s
  maxIdleTimeout: 60s
  keepAlivePeriodTimeout: 10s
  nextProtos: ["aloh-networking"]
  stunHost: "164.90.163.153"
  stunPort: "3478"
  turnHost: "164.90.163.153"
  turnPort: "3478"
  newSDPTimeout: 5s
  sendInStreamTimeout: 5s
  establishConnTimeout: 30s
  datagramLogTargetCount: 500
  fetchLogTargetCount: 100
  disconnectedTimeout: 20s

handler:
  sendChatTimeout: 5s
  sendVideoTimeout: 5s
  sendVoiceTimeout: 5s
  connectTimeout: 5s
  disconnectTimeout: 5s
  fetchOnlineTimeout: 5s